name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Build C# code
      run: dotnet build
    - name: Run C# tests
      run: dotnet test
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build typescript code
      working-directory: ./DotnetTemplate.Web
      run: |
          npm ci
          npm run build
    - name: Run typescript tests
      working-directory: ./DotnetTemplate.Web
      run: npm t
    - name: Run typescript linting
      working-directory: ./DotnetTemplate.Web
      run: npm run lint
    - name: Report completed to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    
